linters:
  enable-all: true
  disable:
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - lll
    - scopelint
    - depguard
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
run:
  deadline: 4m
  skip-files:
    - "zz_generated.*\\.go$"
  skip-dirs:
    - third_party
